### ISSUE TITLE
Support EAP version

### ISSUE THREAD

**Issue by dbourguignon** [codota/tabnine-intellij#4]
This stopped working with the RubyMine 2019.3 EAP version

It maybe just a flag in the meta data

Thanks for the nice work!

**Comment by Danmou** [comment]
@zxqfl The official release of 2019.3 is supposed to happen this month, so it would be good to release an update to the plugin before that! Otherwise it's gonna break for everyone.

**Comment by cosmtrek** [comment]
I've submit a PR https://github.com/zxqfl/tabnine-intellij/pull/8 to fix this problem.

**Comment by balta2ar** [comment]
@zxqfl 2019.3 is out today. Could you please update the plugin?

**Comment by raybotha** [comment]
I'm usually on an EAP version and this would be my most useful plugin, it just never reports as being compatible to IntelliJ EAP versions? Surely it's not necessary to have to patch the supported version every time there's an update, can't we just assume it will work until proven otherwise? We are developers after all, I'd rather disable a broken plugin than not have it at all.

**Comment by amircodota** [comment]
Hi @raybotha 

We released version 0.1.8, which does not limit new versions, so from now on, any EAP build will be supported.

Closing for now - feel free to re-open if needed.

Amir
